### PR TITLE
Update recipe and version (0.5.3)

### PR DESCRIPTION
**Pull request by Anthchirp**
mostly regenerated using grayskull

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
I've added myself as maintainer if you don't mind - if you do feel free to remove me 🙂

**Comment by alexmojaki** [comment]
Hey, thanks for your help. Can I ask why you'd like to be a maintainer? What effect does it have?

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
Maintainers can
* merge pull requests
* and also modify incoming pull requests (eg. those from bots for updates/rebuilds/architecture changes)

basically it's an offer to help.

**Comment by alexmojaki** [comment]
Sounds good, thanks!

**Pull request merged**
